name: Deploy to Staging

on:
  push:
    branches:
      - staging/main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      RECIPIENTS: "pranav.sonawane@pyrack.com,ruchika.purohit@pyrack.com,hrishabh.mandhan@pyrack.com,ayush.vinchurkar@pyrack.com"
      REPLY_TO: "hrishabh.mandhan@pyrack.com"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose (no cache)
        run: docker compose -f docker-compose-staging.yml build --no-cache

      - name: Deploy Docker Compose
        run: docker compose -f docker-compose-staging.yml up -d

      - name: Clean Docker System
        run: docker system prune -f --all

      - name: Get Git Commit Info
        id: gitinfo
        run: |
          COMMIT_LOG=$(git log -1 --pretty=format:"%h by %an on %ad: %s" --date=iso)
          echo "log_entry=<li>$COMMIT_LOG</li>" >> $GITHUB_OUTPUT

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "${{ github.workflow }} - Build #${{ github.run_number }} - ${{ job.status }}"
          to: ${{ env.RECIPIENTS }}
          reply_to: ${{ env.REPLY_TO }}
          content_type: text/html
          body: |
            <html>
              <body>
                <div style="border: 4px solid ${{ job.status == 'success' && 'green' || 'red' }}; padding: 10px;">
                  <h2>${{ github.workflow }} - Build #${{ github.run_number }}</h2>
                  <div style="background-color: ${{ job.status == 'success' && 'green' || 'red' }}; padding: 10px;">
                    <h3 style="color: white;">Pipeline Status: ${{ job.status }}</h3>
                  </div>
                  <p>Git Commit changes for the build:
                    ${{ steps.gitinfo.outputs.log_entry }}
                    <br>Check the <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">workflow logs</a>.
                  </p>
                </div>
              </body>
            </html>
