# .github/workflows/deploy.yml
name: CI/CD to Physical Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1️⃣  Start an ssh-agent and feed it the private key stored in secrets
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 2️⃣  Add the server’s host key once so StrictHostKeyChecking can stay on
    - name: Trust server fingerprint
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    # 3️⃣  Run your deployment commands
    - name: Deploy via SSH
      run: |
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'EOS'
          set -e                      # fail fast on the server too
          cd ~/myapp                  # simpler: you’re already that user
          git pull origin main
          docker compose -f docker-compose-prod.yml down --remove-orphans
          docker compose -f docker-compose-prod.yml pull
          docker compose -f docker-compose-prod.yml up -d --build
          docker system prune -f
        EOS


# jobs:
#   deploy:
#     name: Deploy to Physical Server
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Setup SSH
#       uses: webfactory/ssh-agent@v0.9.0
#       with:
#         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#     - name: Deploy via SSH
#       run: |
#         ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
#           cd /home/${{ secrets.SSH_USER }}/myapp  # Change this path as needed
#           git pull origin main
#           docker compose -f docker-compose-prod.yml down --remove-orphans
#           docker compose -f docker-compose-prod.yml pull
#           docker compose -f docker-compose-prod.yml up -d --build
#           docker system prune -f
#         EOF
