name: CI/CD to Physical Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Physical Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ubuntu/piloofe
          git pull origin main
          docker compose -f docker-compose-prod.yml down --remove-orphans
          docker compose -f docker-compose-prod.yml pull
          docker compose -f docker-compose-prod.yml up -d --build
          docker system prune -f
        EOF
